export const appIpcs = {
  login: 'login',
  createUser: 'createUser',
  updateUser: 'updateUser',
  deleteUser: 'deleteUser',
  retrieveAllUsers: 'retrieveAllUsers',
  retrieveUser: 'retrieveUser',
  updateStatusUser: 'updateStatusUser',
  createTask: 'createTask',
  updateTask: 'updateTask',
  deleteTask: 'deleteTask',
  retrieveAllTasks: 'retrieveAllTasks',
  retrieveTask: 'retrieveTask',
  assignTaskToUser: 'assignTaskToUser',
  assignTaskToSprint: 'assignTaskToSprint',
  createTaskType: 'createTaskType',
  updateTaskType: 'updateTaskType',
  deleteTaskType: 'deleteTaskType',
  retrieveTaskType: 'retrieveTaskType',
  retrieveAllTasksType: 'retrieveAllsTaskType',
  createTaskStatus: 'createTaskStatus',
  updateTaskStatus: 'updateTaskStatus',
  deleteTaskStatus: 'deleteTaskStatus',
  retrieveTaskStatus: 'retrieveTaskStatus',
  retrieveAllTasksStatus: 'retrieveAllTasksStatus',
};
